# Site settings
baseurl = "https://dantanner.com/"
title = "Dan Tanner"
themesDir = "themes"
theme = "hermit-v2"

languageCode = "en-us"
#defaultContentLanguage = "en"
#defaultContentLanguageInSubdir = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Disable comments by leaving disqusShortname empty
disqusShortname = ""

PygmentsCodeFences = true
#PygmentsStyle = "arduino"
pygmentsUseClasses = true

rssLimit = 10

copyright = ""
enableEmoji = true

[params.author]
  name = "Dan Tanner"
  about = "Personal and Semi-Professional Blog"

[taxonomies]
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # description = "CHANGE ME SITE DESCRIPTION"
  # images = [""]
  themeColor = "#494f5c"

  #homeSubtitle = "CHANGE ME HOME SUBTITLE"
  footerCopyright = ""
  # bgImg = ""
  # gitUrl = "https://github.com/1bl4z3r/hermit-V2/tree/staging"

  justifyContent = false

  relatedPosts = true
  code_copy_button = true

  homeSubtitlePrinter = true
  scrollToTop = true
  global_mathjax = false
  readTime = true
  readTimeSeparator = " | "
  # legacyLayout = false
  shareSocial = true
  # googleTagManager = "GTM-XXXXXXXX"
  # tagSymbol = "#"
  # categorySymbol = "⊲"

  [[params.socialLinks]]
    name = "github"
    url = "https://www.github.com/dtanner"

  [[params.socialLinks]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/omgdan/"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "post/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 20

